name: Check and publish

on:
  push:
    branches: [master, develop]

  pull_request:
    branches: [master, develop]

  release:
    types: [created]

jobs:
  quality:
    name: Code QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install black flake8 isort
      - run: black --version
      - run: isort --check .
      - run: black --check .
      - run: flake8 --max-line-length 200 .

  checks:
    strategy:
      fail-fast: false
      matrix:
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    name: Python ${{ matrix.python-version }} on ${{ matrix.platform }} (${{ matrix.method }})
    runs-on: ${{ matrix.platform }}
    needs: quality

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov isort black flake8
          pip install --upgrade setuptools wheel

      # - run: python setup.py develop
      - run: pip install -r requirements.txt
      - run: pip install -e . -r tests/requirements.txt
      - run: pip install -r tests/requirements.txt
      - run: pip freeze
      - run: env | sort
      - run: ECCODES_PYTHON_USE_FINDLIBS=1 python -m eccodes selfcheck
      - run: pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: 'false'
